tasks:
  checkA:
    action: !org.jetbrains.amper.plugins.checker.runCheckA
      moduleName: ${module.name}
  runCheckB:
    action: !org.jetbrains.amper.plugins.checker.runCheckB
      moduleName: ${module.name}

checks:
  - checkA # shorthand
  - performedBy: runCheckB
    name: checkB
